import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner"
import { Navbar } from "@/components/Navbar"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} font-sans antialiased min-h-screen flex flex-col bg-white selection:bg-[#10b981]/20 selection:text-[#065f46]`}
      >
        <Navbar />
        <main className="flex-1 bg-gray-50/50">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
